version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - dog-rescuer-adoption-network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - dog-rescuer-adoption-network

  dog-rescuer-service:
    build:
      context: dog-rescuer
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - zookeeper
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - dog-rescuer-adoption-network

  dog-adoption-center-service:
    build:
      context: dog-adoption-center
      dockerfile: Dockerfile
    ports:
    - 9090:9090
    depends_on:
      - kafka
      - zookeeper
      - dog-rescuer-service
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - dog-rescuer-adoption-network

networks:
  dog-rescuer-adoption-network:
